use library
go
--CREATE TABLE [TB_ReaderType](
--	[rdType] smallint NOT NULL,
--	[rdTypeName] nvarchar(20) NOT NULL,
--	[CanLendQty] int NULL,
--	[CanLendDay] int NULL,
--	[CanContinueTimes] int NULL,
--	[PunishRate] float NULL,
--	[DateValid] smallint not NULL DEFAULT ((0)),
-- PRIMARY KEY ([rdType]),
-- UNIQUE ([rdTypeName])
--)
--insert into [TB_ReaderType]	values(10,'教师',12,60,2,0.05,0);
--insert into [TB_ReaderType]	values(20,'本科生',8,30,1,0.05,4);
--insert into [TB_ReaderType]	values(21,'专科生',8,30,1,0.05,3);
--insert into [TB_ReaderType]	values(30,'硕士研究生',8,30,1,0.05,3);
--insert into [TB_ReaderType]	values(31,'博士研究生',8,30,1,0.05,4);
--GO
--create table TB_Reader(
--rdID int not null,
--rdName nvarchar(20) null,
--rdSex nchar(1) null,
--rdType smallint not null,
--rdDept nvarchar(20) null,
--rdPhone varchar(25) null,
--rdEmail nvarchar(25) null,
--rdDateReg datetime null,
--rdPhoto nvarchar(100) null,
--rdStatus nchar(2) not null,
--rdBorrowQty int not null default((0)),
--rdPwd nvarchar(20) not null default(('123')),
--rdAdminRoles smallint not null,
--primary key (rdID),
--foreign key(rdType) references TB_ReaderType(rdType))
----insert into TB_Reader values(1,'王丹','男',20,'软工11702','23425679801','4538907956@qq.com','2019-12-18','paint.jpg','有效',0,'wd123',0)
--select * from TB_Reader
--insert into TB_Reader values(2,'王丹尼','女',20,'软工11702','23465679801','4638907956@qq.com',getdate(),'paint1.jpg','有效',0,'wdn123',0)
--create table TB_Book(
--bkID int not null,
--bkCode nvarchar(20),
--bkName nvarchar(50),
--bkAuthor nvarchar(30),
--bkPress nvarchar(50),
--bkDatePress dateTime,
--bkISBN nvarchar(15),
--bkLanguage smallint,
--bkPages int,
--bkPrice money,
--bkDateIn datetime,
--bkBrief text,
--bkCover nvarchar(50),
--bkStatus nchar(2),
--primary key (bkID))
--insert into TB_Book values(1,'001','你当像鸟飞往你的山','塔拉 · 韦斯特弗','南海出版公司','2019-11-1','9787544276986',1,456,56.1,getdate(),'人们只看到我的与众不同：一个十七岁前从未踏入教室的大山女孩，却戴上一顶学历的高帽，熠熠生辉。
--只有我知道自己的真面目：我来自一个极少有人能想象的家庭。我的童年由垃圾场的废铜烂铁铸成，那里没有读书声，只有起重机的轰鸣。不上学，不就医，是父亲要我们坚持的忠诚与真理。父亲不允许我们拥有自己的声音，我们的意志是他眼中的恶魔。
--哈佛大学，剑桥大学，哲学硕士，历史博士……我知道，像我这样从垃圾堆里爬出来的无知女孩，能取得如今的成就，应当感激涕零才对。但我丝毫提不起热情。
--我曾怯懦、崩溃、自我怀疑，内心里有什么东西腐烂了，恶臭熏天。
--直到我逃离大山，打开另一个世界。
--那是教育给我的新世界，那是我生命的无限可能。','paint3.jpg','在馆')
--select * from TB_Book
--alter table TB_Book
--add bkCatalog nvarchar(15)
--update TB_Book set bkCatalog='I054' where bkID=1
--create table TB_Borrow(
--BorrowID numeric(12,0) primary key not null,
--rdID int,
--bkID int,
--ldContinueTimes int,
--ldDateOut DateTime,
--ldDateRetPlan Datetime,
--ldDateRetAct Datetime,
--ldOverDay int,
--ldOverMoney Money,
--ldPunishMoney Money,
--isHasReturn bit default((0)),
--operatorLend nvarchar(20),
--operatorRet nvarchar(20),
--foreign key(rdID) references TB_Reader(rdID),
--foreign key(bkID) references TB_Book(bkID)
--)